"""empty message

Revision ID: 809982afd29c
Revises: 9d30cbbaaba5
Create Date: 2025-04-15 00:17:32.985066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809982afd29c'
down_revision = '9d30cbbaaba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
